check if prod deployment

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -12,9 +12,13 @@ on:
 
 jobs:
   build:
-    if: ${{ startsWith(github.ref, 'refs/tags') }}
     runs-on: ubuntu-latest
     steps:
+    - name: Check is it a production deployment?
+      if: ${{ (inputs.environment == 'test-and-prod' || inputs.environment == 'prod') && !startsWith(github.ref, 'refs/tags') }}
+      run: |
+        echo "::error file=deploy-main.yml,line=19,col=7,endColumn=129::You can only run the deploy workflow on a release tag for production deployment."
+        exit 1
     - name: log a message test-and-prod
       if: inputs.environment == 'test-and-prod'
       run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to test-and-prod ${{ github.sha }}"
@@ -24,11 +28,3 @@ jobs:
     - name: log a message prod
       if: inputs.environment == 'prod'
       run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to prod ${{ github.sha }}"
-  report-error:
-    if: ${{ !startsWith(github.ref, 'refs/tags') }}
-    runs-on: ubuntu-latest
-    steps:
-    - name: log a message
-      run: |
-        echo "::error file=deploy-main.yml,line=6,col=5,endColumn=50::You can only run the deploy workflow on a release tag. ${{ github.sha }}"
-        exit 1
